version: '3'
services:

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
#    volumes:
#      - ./data/db:/data/db
    networks:
      - app-network

  app:
    build: '.'
    ports:
      - '3000:3000'
    volumes:
      - ./:/node-app
    depends_on:
      - mongo
    networks:
      - app-network  

networks: 
  app-network:
    driver: bridge